# Generated by Django 3.1.7 on 2021-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='id',
            new_name='uuid',
        ),
    ]
